### ISSUE TITLE
I can not see the animation.

### ISSUE THREAD

**Issue by YeisonVelez11** [ppisljar/image-morph-js#2]
Is this a morphy animation? If so, how can I see the generated animation? Only the images are generated.

**Comment by everythingability** [comment]
Hi...

I did all the points making, but got this. (Nice bit of work, if you can get it working...)

EXCEPTION: Error during evaluation of "click"
angular2-all.umd.js:28691 EXCEPTION: Error during evaluation of "click"
angular2-all.umd.js:28691 ORIGINAL EXCEPTION: TypeError: Cannot read property 'length' of undefined
angular2-all.umd.js:28691 ORIGINAL STACKTRACE:
angular2-all.umd.js:28691 TypeError: Cannot read property 'length' of undefined
    at Function.ImgWarper.Point.weightedAverage (imgwarp.js:255)
    at ImgWarper.AffineDeformation.pointMover (imgwarp.js:79)
    at ImgWarper.Warper.warp (imgwarp.js:33)
    at ImgWarper.Animator.generate (imgwarp.js:412)
    at app.WarpResultComponent.ng.core.Component.Class.constructor.generate (warp-result.component.js:55)
    at ChangeDetector_class1_0.handleEventInternal (viewFactory_class1:480)
    at ChangeDetector_class1_0.AbstractChangeDetector.handleEvent (angular2-all.umd.js:10630)
    at AppView.triggerEventHandlers (angular2-all.umd.js:13945)
    at eval (viewFactory_class1:787)
    at angular2-all.umd.js:28048
angular2-all.umd.js:28691 ERROR CONTEXT:
angular2-all.umd.js:28691 
EventEvaluationErrorContext {element: button.btn.btn-default, componentElement: warp-result, context: app.W…t.ng.c…e.C…t.C…s.constructor, locals: {…}, injector: Injector}
angular2-polyfills.js:143 Uncaught 
EventEvaluationError {_wrapperMessage: "Error during evaluation of "click"", _originalException: TypeError: Cannot read property 'length' of undefined
    at Function.ImgWarper.Point.weightedAvera…, _originalStack: "TypeError: Cannot read property 'length' of undefi…morph-2/lib/angular2/angular2-all.umd.js:28048:37", _context: EventEvaluationErrorContext, _wrapperStack: "Error: Error during evaluation of "click"↵    at E…orph-2/lib/angular2/angular2-all.umd.js:13146:41)"}
﻿
​

**Comment by everythingability** [comment]
Oh hang on. Working now... maybe I added too many points, changed my mind about one pic...

Wow!
